-- -----------------------------------------------------------------------------
--       CREATION DES REFERENCES DE TABLE
-- -----------------------------------------------------------------------------

ALTER TABLE FACTURE ADD (
     CONSTRAINT FK_FACTURE_COMMANDE
          FOREIGN KEY (CMD_NUM)
               REFERENCES COMMANDE (CMD_NUM));

ALTER TABLE COMMANDE ADD (
     CONSTRAINT FK_COMMANDE_CLIENT
          FOREIGN KEY (CLN_ID)
               REFERENCES CLIENT (CLN_ID));

ALTER TABLE LIVRAISON ADD (
     CONSTRAINT FK_LIVRAISON_COMMANDE
          FOREIGN KEY (CMD_NUM)
               REFERENCES COMMANDE (CMD_NUM));

ALTER TABLE ARTICLE ADD (
     CONSTRAINT FK_ARTICLE_EDITEUR
          FOREIGN KEY (EDT_ID)
               REFERENCES EDITEUR (EDT_ID));

ALTER TABLE LIVRER ADD (
     CONSTRAINT FK_LIVRER_LIVRAISON
          FOREIGN KEY (LIV_NUM)
               REFERENCES LIVRAISON (LIV_NUM));

ALTER TABLE LIVRER ADD (
     CONSTRAINT FK_LIVRER_ARTICLE
          FOREIGN KEY (ART_ISBN)
               REFERENCES ARTICLE (ART_ISBN));

ALTER TABLE CLASSIFIER ADD (
     CONSTRAINT FK_CLASSIFIER_ARTICLE
          FOREIGN KEY (ART_ISBN)
               REFERENCES ARTICLE (ART_ISBN));

ALTER TABLE CLASSIFIER ADD (
     CONSTRAINT FK_CLASSIFIER_CATEGORIE
          FOREIGN KEY (CAT_ID)
               REFERENCES CATEGORIE (CAT_ID));

ALTER TABLE CONCERNER ADD (
     CONSTRAINT FK_CONCERNER_ARTICLE
          FOREIGN KEY (ART_ISBN)
               REFERENCES ARTICLE (ART_ISBN));

ALTER TABLE CONCERNER ADD (
     CONSTRAINT FK_CONCERNER_PROMOTION
          FOREIGN KEY (PRM_ID)
               REFERENCES PROMOTION (PRM_ID));

ALTER TABLE APPARTENIR ADD (
     CONSTRAINT FK_APPARTENIR_GENRE
          FOREIGN KEY (GNR_ID)
               REFERENCES GENRE (GNR_ID));

ALTER TABLE APPARTENIR ADD (
     CONSTRAINT FK_APPARTENIR_ARTICLE
          FOREIGN KEY (ART_ISBN)
               REFERENCES ARTICLE (ART_ISBN));

ALTER TABLE AVOIR ADD (
     CONSTRAINT FK_AVOIR_FACTURE
          FOREIGN KEY (FCT_NUM)
               REFERENCES FACTURE (FCT_NUM));

ALTER TABLE AVOIR ADD (
     CONSTRAINT FK_AVOIR_ARTICLE
          FOREIGN KEY (ART_ISBN)
               REFERENCES ARTICLE (ART_ISBN));

ALTER TABLE ECRIRE ADD (
     CONSTRAINT FK_ECRIRE_ARTICLE
          FOREIGN KEY (ART_ISBN)
               REFERENCES ARTICLE (ART_ISBN));

ALTER TABLE ECRIRE ADD (
     CONSTRAINT FK_ECRIRE_AUTEUR
          FOREIGN KEY (AUT_ID)
               REFERENCES AUTEUR (AUT_ID));

ALTER TABLE CONTENIR ADD (
     CONSTRAINT FK_CONTENIR_COMMANDE
          FOREIGN KEY (CMD_NUM)
               REFERENCES COMMANDE (CMD_NUM));

ALTER TABLE CONTENIR ADD (
     CONSTRAINT FK_CONTENIR_ARTICLE
          FOREIGN KEY (ART_ISBN)
               REFERENCES ARTICLE (ART_ISBN));

ALTER TABLE FOURNIR ADD (
     CONSTRAINT FK_FOURNIR_FOURNISSEUR
          FOREIGN KEY (FRN_ID)
               REFERENCES FOURNISSEUR (FRN_ID));

ALTER TABLE FOURNIR ADD (
     CONSTRAINT FK_FOURNIR_ARTICLE
          FOREIGN KEY (ART_ISBN)
               REFERENCES ARTICLE (ART_ISBN));