-- -----------------------------------------------------------------------------
--       CREATION DES CHECK
-- -----------------------------------------------------------------------------

ALTER TABLE CONCERNER ADD CONSTRAINT CK_CONCERNER 
	CHECK (CON_POURCENTAGE BETWEEN 0 AND 100);

ALTER TABLE ARTICLE ADD CONSTRAINT CK_ARTICLE CHECK(
	ART_ISBN BETWEEN 1000000000000 AND 9999999999999);

ALTER TABLE AUTEUR ADD CONSTRAINT CK_AUTEUR CHECK(
	AUT_SEXE = 'M' OR AUT_SEXE = 'F');

ALTER TABLE CLIENT ADD  CONSTRAINT CK_CLIENT_EMAIL CHECK(
	REGEXP_LIKE(CLN_EMAIL,'.*@.*\.(com|fr)'));

ALTER TABLE CLIENT ADD CONSTRAINT CK_CLIENT_PASSWORD CHECK (
	REGEXP_LIKE(CLN_MOT_PASSE,'^.*[0-9]', 'c') AND REGEXP_LIKE(CLN_MOT_PASSE, '^[a-zA-Z][a-zA-Z0-9]{7,}$', 'c'));

ALTER TABLE CLIENT ADD CONSTRAINT CK_CLIENT_SEXE CHECK(
	CLN_SEXE = 'M' OR CLN_SEXE = 'F');