-- -----------------------------------------------------------------------------
--       CREATION DES SEQUENCES
-- -----------------------------------------------------------------------------

CREATE SEQUENCE SEQ_CATEGORIE
INCREMENT BY 1 START WITH 1
MAXVALUE 999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_EDITEUR
INCREMENT BY 1 START WITH 1
MAXVALUE 99999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_AUTEUR
INCREMENT BY 1 START WITH 1
MAXVALUE 99999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_PROMOTION
INCREMENT BY 1 START WITH 1
MAXVALUE 9999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_FOURNISSEUR
INCREMENT BY 1 START WITH 1
MAXVALUE 99999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_GENRE
INCREMENT BY 1 START WITH 1
MAXVALUE 999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_LIVRAISON
INCREMENT BY 1 START WITH 1
MAXVALUE 99999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_COMMANDE
INCREMENT BY 1 START WITH 1
MAXVALUE 99999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_CLIENT
INCREMENT BY 1 START WITH 1
MAXVALUE 99999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE SEQ_FACTURE
INCREMENT BY 1 START WITH 1
MAXVALUE 9999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;