-- -----------------------------------------------------------------------------
--       DROP TABLES
-- -----------------------------------------------------------------------------

DROP TABLE AUTEUR CASCADE CONSTRAINTS;

DROP TABLE CATEGORIE CASCADE CONSTRAINTS;

DROP TABLE FACTURE CASCADE CONSTRAINTS;

DROP TABLE FOURNISSEUR CASCADE CONSTRAINTS;

DROP TABLE COMMANDE CASCADE CONSTRAINTS;

DROP TABLE LIVRAISON CASCADE CONSTRAINTS;

DROP TABLE PROMOTION CASCADE CONSTRAINTS;

DROP TABLE CLIENT CASCADE CONSTRAINTS;

DROP TABLE GENRE CASCADE CONSTRAINTS;

DROP TABLE ARTICLE CASCADE CONSTRAINTS;

DROP TABLE EDITEUR CASCADE CONSTRAINTS;

DROP TABLE LIVRER CASCADE CONSTRAINTS;

DROP TABLE CLASSIFIER CASCADE CONSTRAINTS;

DROP TABLE CONCERNER CASCADE CONSTRAINTS;

DROP TABLE APPARTENIR CASCADE CONSTRAINTS;

DROP TABLE AVOIR CASCADE CONSTRAINTS;

DROP TABLE ECRIRE CASCADE CONSTRAINTS;

DROP TABLE CONTENIR CASCADE CONSTRAINTS;

DROP TABLE FOURNIR CASCADE CONSTRAINTS;