-- -----------------------------------------------------------------------------
--       DROP INDEX DES TABLES
-- -----------------------------------------------------------------------------

DROP INDEX I_AUTEUR_NOM;

DROP INDEX I_FK_FACTURE_COMMANDE;

DROP INDEX I_DATE;

DROP INDEX I_FOURNISSEUR_NOM;

DROP INDEX I_FK_COMMANDE_CLIENT;

DROP INDEX I_CMD_DATE_MODIF;

DROP INDEX I_FK_LIVRAISON_COMMANDE;

DROP INDEX I_LIVRAISON_DATE;

DROP INDEX I_IDENTIFIANTS;

DROP INDEX I_FK_ARTICLE_EDITEUR;

DROP INDEX I_ARTICLE_TITRE;

DROP INDEX I_FK_LIVRER_LIVRAISON;

DROP INDEX I_FK_LIVRER_ARTICLE;

DROP INDEX I_FK_CLASSIFIER_ARTICLE;

DROP INDEX I_FK_CLASSIFIER_CATEGORIE;

DROP INDEX I_FK_CONCERNER_ARTICLE;

DROP INDEX I_FK_CONCERNER_PROMOTION;

DROP INDEX I_FK_APPARTENIR_GENRE;

DROP INDEX I_FK_APPARTENIR_ARTICLE;

DROP INDEX I_FK_AVOIR_FACTURE;

DROP INDEX I_FK_AVOIR_ARTICLE;

DROP INDEX I_FK_ECRIRE_ARTICLE;

DROP INDEX I_FK_ECRIRE_AUTEUR;

DROP INDEX I_FK_CONTENIR_COMMANDE;

DROP INDEX I_FK_CONTENIR_ARTICLE;

DROP INDEX I_FK_FOURNIR_FOURNISSEUR;

DROP INDEX I_FK_FOURNIR_ARTICLE;